spring.application.name=AurusLogServiceApplication
server.port=1234

zabbix.client.url0=http://192.168.92.195
zabbix.client.url=http://192.168.187.177
zabbix.client.port=8888
zabbix.client.endpoint=/get_logs

logpath.host=/opt/auruspay_switch/log/auruspay/auruspay.log
logpath.atv=c
logpath.ecst=c
logpath.ds=c